In [27]:
# !pip install pandas
#!pip install seaborn
#!pip install openpyxl

In [42]:
import pandas as pd
import seaborn as sns

In [48]:
df= pd.read_excel('Date_Fruit_Datasets.xlsx', sheet_name=None)
df=df['Date_Fruit_Datasets']
df

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,255403,1925.3650,691.8453,477.1796,0.7241,570.2536,0.9785,261028,0.7269,1.4499,...,2.2423,2.3704,2.7202,-25296416768,-19168882688,-18473392128,49.0869,43.0422,42.4153,SOGAY
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502,SOGAY
895,254330,1926.7360,747.4943,435.6219,0.8126,569.0545,0.9925,256255,0.7240,1.7159,...,2.2759,2.5090,2.6951,-22242772992,-19594921984,-17592152064,44.1325,40.7986,40.9769,SOGAY
896,238955,1906.2679,716.6485,441.8297,0.7873,551.5859,0.9604,248795,0.6954,1.6220,...,2.6769,2.6874,2.7991,-26048595968,-21299822592,-19809978368,51.2267,45.7162,45.6260,SOGAY
897,343792,2289.2720,823.8438,534.7757,0.7607,661.6113,0.9781,351472,0.6941,1.5405,...,2.5138,3.0369,3.0865,-31983476736,-20482514944,-21219354624,47.3454,38.6966,39.6738,SOGAY

In [45]:
major_df= df["MAJOR_AXIS"]
major_df

0      837.8484
1      723.8198
2      940.7379
3      827.9804
4      763.9877
         ...
893    691.8453
894    855.4633
895    747.4943
896    716.6485
897    823.8438
Name: MAJOR_AXIS, Length: 898, dtype: float64

In [54]:
class_df= df["Class"]
class_df

0      BERHI
1      BERHI
2      BERHI
3      BERHI
4      BERHI
       ...
893    SOGAY
894    SOGAY
895    SOGAY
896    SOGAY
897    SOGAY
Name: Class, Length: 898, dtype: object

In [58]:
major_df= df[df["Class"]=="BERHI"]
major_df

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,445290,2435.3889,857.8929,663.8074,0.6335,752.9680,0.9940,448000,0.7515,1.2924,...,4.8948,10.0825,8.1471,-35740303360,-30464757760,-27059025920,44.8647,42.0194,37.8889,BERHI
61,375936,2255.8411,817.8654,589.0416,0.6937,691.8501,0.9945,378008,0.7365,1.3885,...,5.8351,13.1056,12.0114,-19649556480,-21339979776,-19707056128,36.7722,38.8620,36.5344,BERHI
62,439650,2447.7371,890.0155,635.1306,0.7005,748.1843,0.9926,442920,0.7633,1.4013,...,4.0996,8.0819,8.6770,-46067900416,-43327778816,-41025200128,50.2533,49.8476,47.6192,BERHI
63,433338,2423.3010,836.3414,664.9469,0.6065,742.7941,0.9932,436301,0.7560,1.2578,...,3.6208,4.0745,6.1444,-48579203072,-42560143360,-34883911680,52.5610,49.6808,44.5522,BERHI
64,500669,2580.3069,913.3773,702.0745,0.6397,798.4182,0.9948,503290,0.7571,1.3010,...,4.0502,6.2261,5.9918,-42263990272,-33475536896,-34506137600,46.3075,41.6845,40.4161,BERHI

In [64]:
minor_df= df[df["Class"]=="SOGAY"]
minor_df[['MINOR_AXIS', 'Class']]

     MINOR_AXIS  Class
804    497.2475  SOGAY
805    520.5521  SOGAY
806    535.5190  SOGAY
807    514.7833  SOGAY
808    513.4503  SOGAY
..          ...    ...
893    477.1796  SOGAY
894    551.5447  SOGAY
895    435.6219  SOGAY
896    441.8297  SOGAY
897    534.7757  SOGAY

[94 rows x 2 columns]

In [65]:
perimeter_df= df[(df["Class"]=="SOGAY") & (df['PERIMETER']>2000)]
perimeter_df[['PERIMETER', 'Class']]

     PERIMETER  Class
804  1927.4420  SOGAY
805  2226.3210  SOGAY
806  2343.2290  SOGAY
807  2168.5410  SOGAY
808  2172.4651  SOGAY
..         ...    ...
893  1925.3650  SOGAY
894  2664.8230  SOGAY
895  1926.7360  SOGAY
896  1906.2679  SOGAY
897  2289.2720  SOGAY

[94 rows x 2 columns]

In [69]:
df[(df["Class"]=="SOGAY") & (df['PERIMETER']>2000) & (df['AREA']>350000)]

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
806,378039,2343.2290,902.6270,535.5190,0.8050,693.7825,0.9889,382265,0.7876,1.6855,...,2.2545,3.5794,3.1576,-33263110144,-22413066240,-29248870400,45.6848,38.2546,43.5166,SOGAY
813,351763,2293.7791,878.5163,513.9243,0.8110,669.2373,0.9843,357372,0.7913,1.7094,...,2.9730,3.0988,3.3927,-48845398016,-33364766720,-34880897024,57.9532,48.7891,49.8772,SOGAY
819,365088,2249.6321,863.3080,541.9211,0.7784,681.7950,0.9916,368189,0.8012,1.5931,...,2.0959,2.4816,2.7834,-30497318912,-22633324544,-25095098368,44.6592,38.7004,41.0996,SOGAY
833,355294,2266.9509,870.8358,521.8104,0.8006,672.5878,0.9887,359343,0.7780,1.6689,...,2.8609,4.5472,3.1222,-27548553216,-19063996416,-28639526912,43.8971,36.8984,44.4692,SOGAY
835,363370,2249.0371,793.2402,586.2938,0.6736,680.1890,0.9930,365942,0.7634,1.3530,...,2.3142,2.4876,2.7035,-37033537536,-26804267008,-29595344896,48.1116,40.5485,44.2552,SOGAY
863,375569,2377.7141,953.8370,504.3600,0.8488,691.5123,0.9897,379477,0.6888,1.8912,...,2.3179,3.1932,4.2625,-35391660032,-23251091456,-27960356864,47.3617,38.4523,42.7170,SOGAY
879,376000,2405.4141,952.5737,506.6357,0.8468,691.9090,0.9826,382645,0.8080,1.8802,...,2.3622,4.9643,3.6943,-30594353152,-19703881728,-31713038336,44.0476,36.1755,45.3407,SOGAY
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687,SOGAY
887,373627,2634.6440,860.8875,555.6307,0.7638,689.7222,0.9715,384588,0.7382,1.5494,...,3.6601,6.9302,6.8205,-20488452096,-14733557760,-14105267200,38.1975,32.0405,31.3667,SOGAY
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502,SOGAY

In [79]:
df[["PERIMETER","AREA"]]

     PERIMETER    AREA
0    2378.9080  422163
1    2085.1440  338136
2    2647.3940  526843
3    2351.2100  416063
4    2160.3540  347562
..         ...     ...
893  1925.3650  255403
894  2664.8230  365924
895  1926.7360  254330
896  1906.2679  238955
897  2289.2720  343792

[898 rows x 2 columns]

In [78]:
df[(df["Class"]=="SOGAY") & (df['PERIMETER']>2000) & (df['AREA']>350000)][['PERIMETER', 'Class', 'AREA']]

     PERIMETER  Class    AREA
806  2343.2290  SOGAY  378039
813  2293.7791  SOGAY  351763
819  2249.6321  SOGAY  365088
833  2266.9509  SOGAY  355294
835  2249.0371  SOGAY  363370
863  2377.7141  SOGAY  375569
879  2405.4141  SOGAY  376000
880  2385.5110  SOGAY  364338
887  2634.6440  SOGAY  373627
894  2664.8230  SOGAY  365924